FROM ubuntu/apache2
RUN echo "Django Project"
RUN echo "---------------------------------------"
RUN echo "---------- Ubuntu Update... -----------"
RUN echo "---------------------------------------"
RUN apt-get -y update
RUN apt-get -y upgrade
RUN echo "Install python"
RUN apt-get -y install python3
RUN apt-get -y install python3-pip
